# Multivariate Regression

In [11]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
# Import dataset
dataset = pd.read_csv('cleaned_and_normalized_training_set.csv')
dataset = dataset.drop('Unnamed: 0', axis=1)
dataset.head()

,Store,DayOfWeek,day,month,year,Sales,Customers,Open,Promo,SchoolHoliday,...,storeType_a,storeType_b,storeType_c,storeType_d,Assortment_a,Assortment_b,Assortment_c,public_holiday,easter,christmas
0,1,5,31,7,2015,5263,0.099708,1,1,1,...,0,0,1,0,1,0,0,0,0,0
1,2,5,31,7,2015,6064,0.112468,1,1,1,...,1,0,0,0,1,0,0,0,0,0
2,3,5,31,7,2015,8314,0.148195,1,1,1,...,1,0,0,0,1,0,0,0,0,0
3,4,5,31,7,2015,13995,0.271600,1,1,1,...,0,0,1,0,0,0,1,0,0,0
4,5,5,31,7,2015,4822,0.100437,1,1,1,...,1,0,0,0,1,0,0,0,0,0

In [13]:
# Initial correlation
corr_matrix = dataset.corr()
corr_matrix["Sales"].sort_values(ascending=False)

Sales                  1.000000
Customers              0.820071
Promo                  0.372715
storeType_b            0.147129
Assortment_c           0.111184
month                  0.064365
Assortment_b           0.059404
SchoolHoliday          0.033987
year                   0.023731
public_holiday         0.014476
easter                 0.011176
christmas              0.008736
Store                  0.006702
storeType_c           -0.004440
Competition           -0.010849
storeType_a           -0.016199
storeType_d           -0.022484
day                   -0.063273
CompetitionDistance   -0.069944
Assortment_a          -0.122784
Promo2                -0.124554
DayOfWeek             -0.183365
Open                        NaN
Name: Sales, dtype: float64

In [14]:
#Split timeseries data into two

from sklearn.model_selection import TimeSeriesSplit
from matplotlib import pyplot

tss = TimeSeriesSplit(n_splits = 3)
X = dataset.drop(labels=['Sales'], axis=1)
y = dataset['Sales']

for train_index, test_index in tss.split(X):
    X_train, X_test = X.iloc[train_index, :], X.iloc[test_index,:]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

In [15]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [16]:
preds = np.array(y_pred)
actuals = np.array(y_test)
def metric(preds, actuals):
    preds = preds.reshape(-1)
    actuals = actuals.reshape(-1)
    assert preds.shape == actuals.shape
    return 100 * np.linalg.norm((actuals - preds) / actuals) / np.sqrt(preds.shape[0])
metric(preds, actuals)

20.622326330463082